import type { Project } from '@shared/types'

export const demoProject: Project = {
  id: 'demo-808',
  name: '808 Starter Groove',
  transport: {
    playing: false,
    bpm: 100,
    stepsPerBar: 16,
    bars: 1,
    swing: 0,
  },
  pads: [
    {
      id: 'pad-kick',
      name: 'Kick',
      color: '#ef4444',
      gain: 0.95,
      attack: 0.001,
      decay: 0.45,
      startOffset: 0,
      loop: false,
      muted: false,
      sample: {
        id: 'pad-kick',
        name: '808 Kick',
        duration: 0,
        sampleRate: 0,
      },
    },
    {
      id: 'pad-snare',
      name: 'Snare',
      color: '#f59e0b',
      gain: 0.85,
      attack: 0.001,
      decay: 0.35,
      startOffset: 0,
      loop: false,
      muted: false,
      sample: {
        id: 'pad-snare',
        name: '808 Snare',
        duration: 0,
        sampleRate: 0,
      },
    },
    {
      id: 'pad-clap',
      name: 'Clap',
      color: '#10b981',
      gain: 0.9,
      attack: 0.001,
      decay: 0.25,
      startOffset: 0,
      loop: false,
      muted: false,
      sample: {
        id: 'pad-clap',
        name: '808 Clap',
        duration: 0,
        sampleRate: 0,
      },
    },
    {
      id: 'pad-hihat',
      name: 'Hi-Hat',
      color: '#3b82f6',
      gain: 0.75,
      attack: 0.001,
      decay: 0.15,
      startOffset: 0,
      loop: false,
      muted: false,
      sample: {
        id: 'pad-hihat',
        name: '808 Closed Hat',
        duration: 0,
        sampleRate: 0,
      },
    },
    {
      id: 'pad-5',
      name: 'Pad 5',
      color: '#a855f7',
      gain: 0.85,
      attack: 0.002,
      decay: 0.2,
      startOffset: 0,
      loop: false,
      muted: false,
    },
    {
      id: 'pad-6',
      name: 'Pad 6',
      color: '#ec4899',
      gain: 0.85,
      attack: 0.002,
      decay: 0.2,
      startOffset: 0,
      loop: false,
      muted: false,
    },
    {
      id: 'pad-7',
      name: 'Pad 7',
      color: '#22d3ee',
      gain: 0.85,
      attack: 0.002,
      decay: 0.2,
      startOffset: 0,
      loop: false,
      muted: false,
    },
    {
      id: 'pad-8',
      name: 'Pad 8',
      color: '#84cc16',
      gain: 0.85,
      attack: 0.002,
      decay: 0.2,
      startOffset: 0,
      loop: false,
      muted: false,
    },
  ],
  pattern: {
    length: 16,
    steps: {
      0: ['pad-kick', 'pad-hihat'],
      1: ['pad-hihat'],
      2: ['pad-hihat'],
      3: ['pad-hihat'],
      4: ['pad-snare', 'pad-hihat'],
      5: ['pad-hihat'],
      6: ['pad-clap', 'pad-hihat'],
      7: ['pad-hihat'],
      8: ['pad-kick', 'pad-hihat'],
      9: ['pad-hihat'],
      10: ['pad-hihat'],
      11: ['pad-hihat'],
      12: ['pad-snare', 'pad-clap', 'pad-hihat'],
      13: ['pad-hihat'],
      14: ['pad-hihat'],
      15: ['pad-hihat'],
    },
  },
}
